# -*- coding: utf-8 -*-
"""PREPROCESAMIENTO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qsdC_ON6B683mn_ibyT5L3wZ7afU_sB

# **PREPROCESAMIENTO**
"""

import pandas as pd
import numpy as np
import os
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder # <--- Importamos OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin
from scipy.stats.mstats import winsorize
from google.colab import drive, files

# Winsorizacion
def winsorize_df(df):
    df_copy = df.copy()
    for col in df_copy.columns:
        if pd.api.types.is_numeric_dtype(df_copy[col]):
            df_copy[col] = winsorize(df_copy[col], limits=[0.05, 0.05])
    return df_copy

class Winsorizer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return winsorize_df(pd.DataFrame(X)).values

# HardClipper
class HardClipper(BaseEstimator, TransformerMixin):
    RANGES = {
        'age': (25, 65),
        'height': (130, 210),
        'weight': (40, 150),
        'ap_hi': (80, 250),
        'ap_lo': (50, 140)
    }
    def fit(self, X, y=None):
        self.feature_names_in_ = ['age', 'height', 'weight', 'ap_hi', 'ap_lo']
        return self
    def transform(self, X):
        X_df = pd.DataFrame(X, columns=self.feature_names_in_)
        for col, (min_val, max_val) in self.RANGES.items():
            X_df[col] = np.clip(X_df[col], min_val, max_val)
        return X_df.values

drive.mount('/content/drive')
ruta = '/content/drive/MyDrive/dataset/datasetsinprepro2.csv'
try:
    df = pd.read_csv(ruta)
except:
    df = pd.read_csv(ruta, sep=';')

target = 'cardio'
y = df[target]
X = df.drop(columns=[target])

numeric_features = ['age', 'height', 'weight', 'ap_hi', 'ap_lo']
all_features = numeric_features + ['cholesterol', 'gluc', 'gender', 'smoke', 'alco', 'active']
existing_features = [f for f in all_features if f in X.columns]
numeric_features = [f for f in numeric_features if f in existing_features]

ordinal_features = ['cholesterol', 'gluc']
binary_features = ['gender', 'smoke', 'alco', 'active']


numeric_pipeline = Pipeline([
    ('clipper', HardClipper()),
    ('imputer', SimpleImputer(strategy='mean')),
    ('winsorizer', Winsorizer()),
    ('scaler', StandardScaler())
])

ordinal_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

binary_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
])

preprocessor = ColumnTransformer([
    ('numeric', numeric_pipeline, numeric_features),
    ('ordinal', ordinal_pipeline, ordinal_features),
    ('binary', binary_pipeline, binary_features)
], remainder='passthrough', verbose_feature_names_out=False)

X_processed = preprocessor.fit_transform(X)

processed_columns = preprocessor.get_feature_names_out()

df_final = pd.DataFrame(X_processed, columns=processed_columns)
df_final[target] = y.values

output_file_name = 'dataset_preprocesado_completo.csv'
output_path_drive = f'/content/drive/MyDrive/dataset/{output_file_name}'
local_file_path = output_file_name

df_final.to_csv(
    output_path_drive,
    index=False,
    sep=';',
    decimal=','
)

print(f"✅ Preprocesamiento (incluyendo OneHotEncoder) completado.")
print(f"✅ Columnas generadas: {list(processed_columns)}")

if os.path.exists(output_path_drive):
    !cp "{output_path_drive}" "{local_file_path}"
    files.download(local_file_path)
    print(f"✅ Archivo descargado.")
else:
    print(f"⚠️ Error al guardar.")